/*
 * TelstraSMSAUS.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/04/2016
 */
using System;

namespace TelstraSMSAUS.PCL
{
    public partial class Configuration
    {
        //The base Uri for API calls
        public static string BaseUri = "https://api.telstra.com/v1";

        //The OAuth 2.0 access token to be set before API calls
        //TODO: Replace the OAuthAccessToken with an appropriate value
        public static string OAuthAccessToken = "TODO: Replace";

    }
}