/*
 * TelstraSMSAUS.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/04/2016
 */
using System;
using TelstraSMSAUS.PCL.Controllers;

namespace TelstraSMSAUS.PCL
{
    public partial class TelstraSMSAUSClient
    {

        /// <summary>
        /// Singleton access to Client controller
        /// </summary>
        public APIController Client
        {
            get
            {
                return APIController.Instance;
            }
        }

        /// <summary>
        /// Client constructor
        /// </summary>
        public TelstraSMSAUSClient(string oAuthAccessToken)
        {
            Configuration.OAuthAccessToken = oAuthAccessToken;
        }
    }
}