/*
 * TelstraSMSAUS.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/04/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Converters;
using TelstraSMSAUS.PCL;

namespace TelstraSMSAUS.PCL.Models
{
    public class MessageStatus : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string to;
        private string receivedTimestamp;
        private string sentTimestamp;
        private ResponseStatusEnum status;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("to")]
        public string To 
        { 
            get 
            {
                return this.to; 
            } 
            set 
            {
                this.to = value;
                onPropertyChanged("To");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("receivedTimestamp")]
        public string ReceivedTimestamp 
        { 
            get 
            {
                return this.receivedTimestamp; 
            } 
            set 
            {
                this.receivedTimestamp = value;
                onPropertyChanged("ReceivedTimestamp");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sentTimestamp")]
        public string SentTimestamp 
        { 
            get 
            {
                return this.sentTimestamp; 
            } 
            set 
            {
                this.sentTimestamp = value;
                onPropertyChanged("SentTimestamp");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("status", ItemConverterType = typeof(StringEnumConverter))]
        public ResponseStatusEnum Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 