/*
 * TelstraSMSAUS.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/04/2016
 */
 using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
		
namespace TelstraSMSAUS.PCL.Models
{
    [JsonConverter(typeof(StringEnumConverter))]		
    public enum ResponseStatusEnum
    {
        PEND, //The message is pending and has not yet been sent to the intended recipient
        SENT, //The message has been sent to the intended recipient, but has not been delivered yet
        DELIVRD, //The message has been delivered to the intended recipient
        READ, //The message has been read by intended recipient and the recipient's response has been received
    }
} 