/*
 * TelstraSMSAUS.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/04/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TelstraSMSAUS.PCL;

namespace TelstraSMSAUS.PCL.Models
{
    public class SendMessageResponse : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string messageId;

        /// <summary>
        /// The unique id to identity the message sent. 
        /// </summary>
        [JsonProperty("messageId")]
        public string MessageId 
        { 
            get 
            {
                return this.messageId; 
            } 
            set 
            {
                this.messageId = value;
                onPropertyChanged("MessageId");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 